["Dragon Priest Armor"]
	#Defines armor values for Dragon Priest armor. Default is [6, 9, 12, 6]
	#[feet, legs, chest, head]
	dragonsteel_armor_values = [12, 18, 24, 14]

["Dragon Priest Masks"]
	#Defines armor values for Dragon Priest armor. Default is [6, 9, 12, 6]
	#[feet, legs, chest, head]
	dragonsteel_armor_values = [2, 2, 2, 10]
