#Ring works while in the player's enderchest
worksInEnderchest = false
#Items are instantly added to player inventory
instantMode = true
#Number of blocks distance the ring will pull items towards the player
# Default: 8
# Range: 1 ~ 16
pullRange = 8
#Number of blocks distance that a coal block prevents attraction
# Default: 8
# Range: 1 ~ 16
bockingDistance = 8
