#Ring works while in the player's enderchest
worksInEnderchest = false
#Delay between repair ticks, higher is slower repair
# Default: 120
# Range: 45 ~ 1200
repairDelay = 45
#Repair modes: 0 = All Slots, 1 = Hotbar Only, 2 = Main Inventory Only, 3 = Armor & Shield Only
# Default: 0
# Range: 0 ~ 3
repairModes = 0
